# system setup
house_bin: ./bin
parameters_dir: ./parameters

# image calibration
calib_gaussian_kernal: [27, 27]
calib_gaussian_iteration: 20
calib_contrast_trans_alpha: 5
calib_contrast_trans_beta: -100
#calib_contrast_trans_beta: -70

# image crop
crop_y_min: 150
crop_y_max: 1150
crop_x_min: 150
crop_x_max: 1750

# background removal
bg_threshold_block_size: 501
bg_threshold_offset: 18

# contour detection
canny_upper_percentile: 80

# quality filtering
min_size: 30
max_size: 2000000
min_circularity: 0.2
max_circularity: 1
small_size_area: 80
small_size_circularity: 0.85
min_convexity: 0.2
max_convexity: 1
min_inertia: 0.2
max_inertia: 1
min_dist: 3
min_dist_pin: 3
circularity_threshold: 0.85
circularity_threshold_very_bad: 0.5

# multi-colony segmentation
area_segment_min: 300
area_segment_max: 50000
segment_bias: 10
filter_bias: 20
size_sub_sample: 10000
post_min_size: 30
post_min_circularity: 0.5
post_min_convexity: 0.5
post_min_inertia: 0.5
random_walker_beta: 2000
random_walker_method: bf
random_walker_maxi_size: 17

# farthest_points
farthest_points_iteration: 10
#num_of_colonies: 20

# visualization
colony_qc_image_spacing: 100
colony_qc_image_label_size: 2
colony_qc_image_thickness: 5
plate_qc_macos_colony_contour_pixel: 2
plate_qc_macos_image_scale_factor: 0.5
plate_qc_macos_image_width_bias: 15
plate_qc_macos_image_height_bias: 120
plate_qc_macos_confirm_window: [160, 90]
plate_qc_macos_text_size_large: 20
plate_qc_macos_text_size_small: 16
plate_qc_macos_text_size_button: 16
colony_qc_macos_image_scale_factor: 0.5
colony_qc_macos_image_width_bias: 15
colony_qc_macos_image_height_bias: 120
colony_qc_macos_confirm_window: [285, 90]
colony_qc_macos_colony_show_bias: 30
colony_qc_macos_colony_window_bias: 150
colony_qc_macos_colony_contour_pixel: 2
colony_qc_macos_colony_label_size: 1
colony_qc_macos_colony_label_thickness: 2
colony_qc_macos_text_size_large: 20
colony_qc_macos_text_size_mid: 18
colony_qc_macos_text_size_small: 16
colony_qc_macos_text_size_button: 16
plate_qc_mswin10_colony_contour_pixel: 2
plate_qc_mswin10_image_scale_factor: 0.5
plate_qc_mswin10_image_width_bias: 15
plate_qc_mswin10_image_height_bias: 125
plate_qc_mswin10_confirm_window: [160, 100]
plate_qc_mswin10_text_size_large: 16
plate_qc_mswin10_text_size_small: 14
plate_qc_mswin10_text_size_button: 14
colony_qc_mswin10_image_scale_factor: 0.5
colony_qc_mswin10_image_width_bias: 15
colony_qc_mswin10_image_height_bias: 140
colony_qc_mswin10_confirm_window: [315, 100]
colony_qc_mswin10_colony_show_bias: 30
colony_qc_mswin10_colony_window_bias: 195
colony_qc_mswin10_colony_contour_pixel: 2
colony_qc_mswin10_colony_label_size: 1
colony_qc_mswin10_colony_label_thickness: 2
colony_qc_mswin10_text_size_large: 16
colony_qc_mswin10_text_size_mid: 15
colony_qc_mswin10_text_size_small: 14
colony_qc_mswin10_text_size_button: 14
